Petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('Petstagram.accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('Petstagram.common.urls')),
    path('pets/', include('Petstagram.pets.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pets/urls.py
from django.urls import path

from pets.views import pets_list, pets_details_or_comment, pets_like, pets_edit, pets_delete, pets_create

urlpatterns = [
    path('', pets_list, name='pet list'),
    path('details/<int:pk>/', pets_details_or_comment, name='pet details or comment'),
    path('like/<int:pk>/', pets_like, name='like pet'),
    path('edit/<int:pk>/', pets_edit, name='edit pet'),
    path('delete/<int:pk>/', pets_delete, name='delete pet'),
    path('create/', pets_create, name='create pet'),
]

common/models.py
from django.db import models
from accounts.models import UserProfile
from pets.models import Pet


class Comment(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    comment = models.TextField(blank=False)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

pets/models.py
from django.db import models


# Create your models here.
from accounts.models import UserProfile


class Pet(models.Model):
    CAT = 'cat'
    DOG = 'dog'
    PARROT = 'parrot'
    PET_TYPES = [
        (CAT, 'Cat'),
        (DOG, 'Dog'),
        (PARROT, 'Parrot'),
    ]

    type = models.CharField(choices=PET_TYPES, max_length=6, blank=False)
    name = models.CharField(max_length=6, blank=False)
    age = models.PositiveIntegerField(blank=False)
    description = models.TextField(blank=False)
    image = models.ImageField(upload_to='pets',)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id}: {self.name} who is a {self.type}'


class Like(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    field = models.CharField(max_length=2)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

templates/landing_page.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <div class="jumbotron parent">
        <img style="width: 100%"
             src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png"
             alt="">
        <div class="absolute">
            <h1 class="display-4">Welcome to Petstagram</h1>
            <p class="lead">Share your pets photos.</p>
            <hr class="my-4">
            <div class="inner cover">
                <h1 class="cover-heading"></h1>
                <div class="row">
                    <div class="col-lg-6">
                        <p class="lead">Already have an account? <br><a href="{% url 'login' %}" class="btn btn-lg btn-secondary">sign
                            in</a></p>
                    </div>
                    <div class="col-lg-6">
                        <p class="lead"> Do not have an account? <br>
                            <a href="{% url 'signup user' %}" class="btn btn-lg btn-secondary">sign up</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pet_create.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <h1 class="text-center">Add new pet photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" class="furniture-form" enctype="multipart/form-data">
                {{ form }}
                {% csrf_token %}
                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

templates/pet_delete.html
{% extends 'shared/site.html' %}
{% block site_content %}
<div class="row">
    <div class="col-lg-12 text-center">
        <h1>Are you sure you want to delete {{ pet.name }}?</h1>
        <div class="m-auto d-flex justify-content-center">
            <div class="m-2">
                <form method="post" action="{% url 'delete pet' pet.id %}">
                    {% csrf_token %}
                    <input type="submit" value="Confirm" class="btn btn-danger"/>
                </form>
            </div>
            <div class="m-2">
                <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/pet_detail.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <div class="d-flex">
        <div class="d-inline p-2 w-50">
            <img src="{{ pet.image.url }}" class="w-50 rounded mx-auto d-block">
        </div>
        <div class="d-inline p-2 w-50">
            <div class="d-flex justify-content-between">
                <h5><u>Type:</u> {{ pet.type }}</h5>
                <h5><u>Name:</u> {{ pet.name }}</h5>
                <h5><u>Age:</u> {{ pet.age }}</h5>
                <h5><u>Owner:</u> <a href="{% url 'user profile' pet.user.user_id %}"> {{ pet.user.user.username }}</a>
                </h5>
            </div>
            <p class="mt-2">Description: {{ pet.description }}</p>
            <div>
                    <a href="{% url 'edit pet' pet.id %}" class="btn btn-success">Edit</a>
                {% if can_delete %}
                    <a href="{% url 'delete pet' pet.id %}" class="btn btn-danger">Delete</a>
                {% endif %}
            </div>
            {% if can_like %}
                {% if not has_likes %}
                    <a href="{% url 'like pet' pet.id %}"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
                {% else %}
                    <a href="{% url 'like pet' pet.id %}"><i class="fa fa-heart" aria-hidden="true"></i></a>
                {% endif %}
            {% endif %}
            <p class="mt-2">Likes: {{ pet.like_set.count }}</p>
        </div>
    </div>
    <div class="d-block" style="background-color: #f1e3e3; padding:2%">
        {% if pet.comment_set.exists %}
            {% for comment in pet.comment_set.all %}
                <div class="box">
                    <a href="{% url 'user profile' user.id %}">{{ comment.user.user.username }}</a>
                    <h5><em>{{ comment.comment }}</em></h5>
                    <hr>
                </div>
            {% endfor %}
        {% else %}
            <div class="box">
                <h3>There are no comments for this pet. </h3>
            </div>
        {% endif %}
        {% if can_comment %}
            <div class="box">
                <form method="post" action="{% url 'pet details or comment' pet.id %}">
                    {{ form }}
                    {% csrf_token %}
                    <button class="btn btn-primary mt-2" type="submit">Add comment</button>
                </form>
            </div>
        {% endif %}
    </div>

{% endblock %}

templates/pet_edit.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <h1 class="text-center">Edit pet photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'edit pet' pet.pk %}" class="furniture-form" enctype="multipart/form-data">
                {{ form }}
                {% csrf_token %}
                <button class="btn btn-primary mt-2" type="submit">Edit</button>
                <img id="img_preview" src="{{ pet.image_url }}" class="w-50 rounded mx-auto d-block">
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
    <script>
        function updateImage() {
            var img = document.getElementById('img_preview');
            var url = this.value;
            img.src = url;
        }
        document.getElementById('img_input').addEventListener('input', updateImage);
    </script>
{% endblock %}

templates/pet_list.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <h1 class='text-center'>All pet photos</h1>
    <div class="row">
        {% for pet in pets %}
            <div class="col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{ pet.image.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ pet.type }} {{ pet.name }}, Age: {{ pet.age }}</h5>
                        <p class="card-text">{{ pet.description }}</p>
                        <a href="{% url 'pet details or comment' pet.id %}" class="btn btn-primary">See details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/signup.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <div class="container-fluid" style="background-image: none">
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <form style="border: 1px solid grey; margin: 10% 0%; padding: 10% 5%" method="post">
                    <h2>Sign up</h2>
                    {{ form }}
                    {% csrf_token %}
                    <button class="btn btn-primary" type="submit">Sign up</button>
                    <span>Have an account?<a href="{% url 'login' %}" style="color:orange">Sign in here</a></span>
                </form>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>
{% endblock %}

templates/user_profile.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <div class="text-center">
        <h1>Hello, {{ profile_user.username }}!</h1>
        <h5>This is your profile</h5>
        {% if profile.profile_picture %}
            <img class="rounded-circle mb-3" src="{{ profile.profile_picture.url }}" alt="Generic placeholder image"
                 width="140"
                 height="140">
        {% else %}
            <img class="rounded-circle mb-3"
                 src="https://t4.ftcdn.net/jpg/00/64/67/63/360_F_64676383_LdbmhiNM6Ypzb3FM4PPuFP9rHe7ri8Ju.jpg"
                 alt="Generic placeholder image"
                 width="140"
                 height="140">
        {% endif %}
        <div class="w-50 m-auto">
            <form action="{% url 'current user profile' %}" method="post" enctype="multipart/form-data">
                {{ form }}
                {% csrf_token %}
                <button class="btn btn-primary">Upload</button>
            </form>
        </div>
    </div>
    <hr>
    {% if pets %}
        <h2 class='text-center'>These are you pet photos</h2>
        <div class="row">
            <div class="row">
                {% for pet in pets %}
                    <div class="col-lg-6">
                        <div class="card" style="width: 18rem;">
                            <img src="{{ pet.image.url }}" class="card-img-top" alt="Image of {{ pet.name }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ pet.type }} {{ pet.name }}, Age: {{ pet.age }}</h5>
                                <p class="card-text">{{ pet.description }}</p>
                                <p class="card-text"><strong>Owner: {{ pet.user.user.username }}</strong></p>
                                <a href="{% url 'pet details or comment' pet.id %}" class="btn btn-primary">See
                                    details</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <div class="text-center">
        <h2>You have no pets</h2>
        <a href="{% url 'create pet' %}" class="btn btn-success">Add Pet Photo</a>
    {% endif %}
{% endblock %}
</div>